### ISSUE TITLE
use QT += KIOCore instead of LIBS += -lKF5KIOCore

### ISSUE THREAD

**Issue by BLumia** [N1coc4colA/NeoStore#2]
Hi and just checkout this project and seems good to me. It also works with *nearly* no change to compile it under the upcoming v20 repo which is based under debian buster and using DTK5.

One of the issue I got when trying to compile it is it cannot found the `kiocore_export.h` header file. Then I checked your project file and found you are using `LIBS +=` to manually linking libraries, which of course won't make it find the correct headers.

`KIOCore` provide qmake modules to use, so you can just use `QT += KIOCore` to use it, then QtCreator will find the correct header file :)

**Comment by N1coc4colA** [comment]
Hello, please excuse me for this long delay. I'm not sure for all of this. I have to tell you that I had this error too and I fixed it for my OS (by editing files, it was a bad include for me, that can be due to what you said). I'll try to use somme pkg_config linking for the future releases. This project is in beta, you can find a compiled version in the already_compiled directory. Some new upload will be done in the next months and after the V20 release (a lot of things will be to change). In waiting of that, please wait for the next release. If it don't fix the error, it's that a bad include have been done in the KDE library. Sorry for this inconvenience.

**Comment by BLumia** [comment]
> I'll try to use somme pkg_config linking for the future releases.

KDE provided qmake modules so why not use the qmake modules directly ny simply edit the [project file](https://github.com/N1coc4colA/NeoStore/blob/master/RitualStore.pro#L1) :)

By the way, DTK also provided its qmake modules so actually using DTK via pkg-config is not the only option :)

> If it don't fix the error, it's that a bad include have been done in the KDE library.

No, `LIBS`only manually link the libs you listed here, it will do nothing about help you finding the correct includes (you need use `INCLUDEPATH`then if you like).

**Comment by N1coc4colA** [comment]
Yes, but the major reason for that is that I use Qt Creator (my IDE) and when I use it, It fails to parse the components of KDE and so on my file are unreadable, Qt Creator won't find the QMake modules. Talking about that, I prefer to tell you that you have a... big and small security flaw in the deepin-store project and its backend (la-store), It's possible to do some big things with, you should use... a system to check user authorization... Else, you can install, freely, any apps, I haven't explore the flaw but it's possible for sure if someone searches a little bit. 
The joys of Open Source development: being able to be warned of flaws. You should fix it before DDE become a world OS, and more with your targets, the enterprises with UOS.

**Comment by BLumia** [comment]
> Yes, but the major reason for that is that I use Qt Creator (my IDE) and when I use it, It fails to parse the components of KDE and so on my file are unreadable, Qt Creator won't find the QMake modules. 

Not quite sure since I use QtCreator from the official package repo and it works out-of-the-box without any issue. Maybe you should checkout why the non-Qt QMake modules are not detected.

> Talking about that, I prefer to tell you that you have a... big and small security flaw in the deepin-store project and its backend (la-store), It's possible to do some big things with, you should use... a system to check user authorization...

Sorry I don't maintain that project, but FYI the v20 change may also comes with the store updates. If you think there are secure issues, feel free to fire a bug in the developer center repo or via email, so related maintainer can looking into the issue and process it :)

Anyway I'd like to close this issue and hope you can get your QtCreator working :)
